### ISSUE TITLE
Can't mount the latest release's DMG on Yosemite

### ISSUE THREAD

**Issue by Khronosx86** [textbrowser/biblioteq#82]
Hi!
I suppose it's because the image is an APFS one. Could you please upload it zipped or in HFS dmg?
Thanks in advance!

**Comment by textbrowser** [comment]
Sure, tomorrow.

**Comment by Khronosx86** [comment]
Thanks!

**Comment by textbrowser** [comment]
Uploaded. :)

**Comment by Khronosx86** [comment]
=)
Unfortunately, it wont work on my mac (doesnt support metal):
`Process:               BiblioteQ [61233]
Path:                  /Applications/BiblioteQ.app/Contents/MacOS/BiblioteQ
Identifier:            com.yourcompany.BiblioteQ
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           BiblioteQ [61233]
User ID:               501

Date/Time:             2020-11-10 22:46:04.719 -0200
OS Version:            Mac OS X 10.10.5 (14F2511)
Report Version:        11
Anonymous UUID:        5B3D2279-E945-DCDC-778F-B9DB5558B9C2


Time Awake Since Boot: 32000 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
  Referenced from: /Applications/BiblioteQ.app/Contents/MacOS/BiblioteQ
  Reason: image not found

Binary Images:
    0x7fff6d3b7000 -     0x7fff6d3ed92f  dyld (353.2.4) <3C068A0D-69D5-3AD6-86D9-6261D3B1564E> /usr/lib/dyld
    0x7fff8b993000 -     0x7fff8bad6fff  libsqlite3.dylib (168.2) <BCB1F77E-2484-3EC4-A1D5-1AE90A407A23> /usr/lib/libsqlite3.dylib
    0x7fff8c01a000 -     0x7fff8cb9bff7  com.apple.AppKit (6.9 - 1348.17) <E485D56D-3E72-34B7-99BB-BFDEE2D07BF5> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff925c3000 -     0x7fff925c3fff  com.apple.Cocoa (6.8 - 21) <EAC0EA1E-3C62-3B28-A941-5D8B1E085FF8> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa

Model: MacBook4,1, BootROM MB41.00C1.B00, 2 processors, Intel Core 2 Duo, 2.4 GHz, 2 GB, SMC 1.31f1
Graphics: Intel GMA X3100, GMA X3100, Built-In
Memory Module: BANK 0/DIMM0, 1 GB, DDR2 SDRAM, 667 MHz, 0x7F7F7F0B00000000, 0x4E5431475436345538484230424E2D334320
Memory Module: BANK 1/DIMM1, 1 GB, DDR2 SDRAM, 667 MHz, 0x7F7F7F0B00000000, 0x4E5431475436345538484230424E2D334320
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x88), Broadcom BCM43xx 1.0 (5.10.131.36.16)
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: FUJITSU MHY2250BH, 250,06 GB
Parallel ATA Device: MATSHITADVD-R   UJ-857E
USB Device: Built-in iSight
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: Composite Device
Thunderbolt Bus:

**Comment by Khronosx86** [comment]
=)
Unfortunately, it wont work on my mac (doesnt support metal)
[Log Error.pdf](https://github.com/textbrowser/biblioteq/files/5520995/Log.Error.pdf)

**Comment by textbrowser** [comment]
I built BQ using 10.15.7. You're using 10.10.5?

**Comment by textbrowser** [comment]
Let me see if a Qt 5.9 build supports Mac 10.10.x. If so, BQ will not include Poppler because Homebrew's Poppler is coupled with Homebrew's Qt.

**Comment by Khronosx86** [comment]
> Let me see if a Qt 5.9 build supports Mac 10.10.x. If so, BQ will not include Poppler because Homebrew's Poppler is coupled with Homebrew's Qt.

Yes, using 10.10.5. Thanks 🙏🏼

**Comment by textbrowser** [comment]
Uploaded BQ built on 10.15.7 using Qt 5.9.9. If it works, it includes changes which have not been released.

**Comment by Khronosx86** [comment]
It didn't work so I decided to install Windows through boot camp, but now I have no clue how to set it up.. only installed PostgreSQL v 13 (haven't installed any additional program through the stack builder) and looked everywhere for a step-by-step to make biblioteQ to work.. I'm clueless and would be of a great help if you could shed some light on how to. Sorry for being a pain in the ass.. Thanks again!

**Comment by textbrowser** [comment]
That's too bad.

Download the BiblioteQ.zip file. BQ is portable so you don't have to install it. After unzipping the file, launch BiblioteQ.exe.

**Comment by textbrowser** [comment]
BQ supports PostgreSQL and SQLite. Becoming familiar with PQ requires effort, so I leave that to the operators.

BiblioteQ

https://github.com/textbrowser/biblioteq/blob/master/Documentation/BiblioteQ.pdf

PostgreSQL

https://github.com/textbrowser/biblioteq/blob/master/Documentation/Administrator%20Guide.pdf

**Comment by Khronosx86** [comment]
Thanks. I've already read both pdfs but didnt help much. Will look elsewhere on how to configure both programs.

**Comment by textbrowser** [comment]
Can you launch BiblioteQ.exe?

**Comment by Khronosx86** [comment]
Yup, I just don’t know how to set up the database/server-client on PostgreSQL and SQLite to make biblioteQ operational. Will look into their documentation.

**Comment by textbrowser** [comment]
Cool. I don't know the process of configuring PQ on Windows. On FreeBSD, after installing the package, I create the schema via postgresql_create_schema.sql. Connectivity is addressed by modifying pg_hba.conf and postgresql.conf.

You don't need to configure SQLite. In BQ, File -> New SQLite Database.

**Comment by Khronosx86** [comment]
Thanks, I've decided for that alternative, though, for some reason, the Author column is not displaying.. it suddenly disappeared.. I re-downloaded the program and the problem persisted. Hope you can help me.
Thanks

**Comment by textbrowser** [comment]
Perhaps you disabled the column. See Select Viewable Columns (right-most tool action, "stacked" lines).

**Comment by Khronosx86** [comment]
Nope, unfortunately that’s not the case. Strange...

![1F1E5DAF-DCED-4194-9C25-898C4F1D0E3D](https://user-images.githubusercontent.com/74218990/99198996-dc45fe00-277a-11eb-98f3-ee0170eb6efe.jpeg)

**Comment by Khronosx86** [comment]
I am also unable to use z39.50 to retrieve data.
![Uploading 12C6D4DD-5410-421C-B34F-E33BA46C7A5A.jpeg…]()

**Comment by textbrowser** [comment]
The All category does not include the column Authors.

**Comment by textbrowser** [comment]
Z39.50 errors are normal. The service may not be available. Try another query mechanism.

**Comment by Khronosx86** [comment]
Yup, did that, just find it strange that all z39.50 give the same error (one at least could work to establish that the problem isn’t at my end - I’ve done port forward in and out both in windows firewall and my router. As for the author’s column, I could swear that at first it showed for me.. for future releases, is it possible to implement modifying multiple entries for a specific option like paperback/hardcover?

**Comment by textbrowser** [comment]
Are you using LoC?

**Comment by textbrowser** [comment]
Just tried LoC using Z39.50 and it worked.

**Comment by textbrowser** [comment]
It's possible that you enabled Populate View on Item Creation, added a book, and saw book columns. Then changed the category to All.

**Comment by textbrowser** [comment]
Adding special bulk updates is not something I would consider as both PQ and SQLite provide those mechanisms.

**Comment by Khronosx86** [comment]
> Just tried LoC using Z39.50 and it worked.


Yes, it worked. Thanks! I looked again at the error log and saw a specific reason why it wouldn’t work - most of my books are Portuguese editions and LoC doesn’t have them in its db.

**Comment by Khronosx86** [comment]
> It's possible that you enabled Populate View on Item Creation, added a book, and saw book columns. Then changed the category to All.

The only option that is enabled is populate view on connect. How d I change the “Categories” option to something else?

**Comment by Khronosx86** [comment]
> Adding special bulk updates is not something I would consider as both PQ and SQLite provide those mechanisms.

I see (:

**Comment by textbrowser** [comment]
Example SQL: UPDATE table_name SET field_name = value WHERE ...
